import java.util.Scanner;
class Demo {
     public static void main(String[] args){
         Scanner input = new Scanner(System.in);
         System.out.println("=================================================================================");
         System.out.println("__          __ _                            _          _ __  __            _         "); 
         System.out.println("\\ \\        / /| |                          | |        (_)  \\/  |          | |                                        ");
         System.out.println(" \\ \\  /\\  / /_| | ___ ___  _,__,___   ___  | |_ ___    _| \\  / | __,_ _,__| |_          ");
         System.out.println("  \\ \\/  \\/ /_ \\ |/ __/ _ \\|  _   _ \\ / _ \\ | __/ _ \\  | | |\\/| |/ _  |  __| __|   ");                                                                                                                                                                              
         System.out.println("   \\  /\\  / __/ | (_| (_) | | | | | |  __/ | || (_) | | | |  | | (_| | |  | |_           ");
         System.out.println("    \\/  \\/\\___|_|\\___\\___/|_| |_| |_|\\___|  \\__\\___/  |_|_|  |_|\\__._|_|   \\__|                                              ");
         System.out.println("================================================================================="    );
         System.out.print("Enter customer phoneNumber : ");
         int number = input.nextInt();
         System.out.print("Enter customer name        : ");
         String name = input.next();
         System.out.println(number);
         System.out.println("=================================================================================");
         System.out.println();

         double Basmathi=250.00,Dhal=180.00,Sugar=150.00,Highland=1200.00,Yoghurt=50.00,Flour=120.00,Soap=160.00;
         System.out.print("Basmathi Qty(kg) - ");
         int bas = input.nextInt();
         System.out.println();
         System.out.print("Dhal Qty(kg) - ");
         int dha = input.nextInt();
         System.out.println();
         System.out.print("Suger Qty(kg) - ");
         int sug = input.nextInt();
         System.out.println();
         System.out.print("Highland Qty - ");
         int hig = input.nextInt();
         System.out.println();
         System.out.print("Yoghurt Qty - ");
         int yog = input.nextInt();
         System.out.println();
         System.out.print("Flour Qty(kg) - ");
         int flo = input.nextInt();
         System.out.println();
         System.out.print("Soap Qty - ");
         int soa = input.nextInt();
         System.out.println();
         System.out.println("+--------------------------------------------------------------------------------+");
         System.out.println("|                        _ __  __         _____ _________                        |        ");
         System.out.println("|                       (_)  \\/  |   /\\   |  __ \\__   __|                        |        ");
         System.out.println("|                        _| \\  / |  /  \\  | |__) | | |                           |        ");
         System.out.println("|                       | | |\\/| | / /\\ \\ |  _  /  | |                           |        ");
         System.out.println("|                       | | |  | |/ ____ \\| | \\ \\  | |                           |        ");
         System.out.println("|                       |_|_|  |_/_/    \\_\\_|  \\_\\ |_|                           |        ");
         System.out.println("|                          NO-123,Keselwatta,panadura.                           |        ");
         System.out.println("|                                                                                |");
         System.out.println("+--------------------------------------------------------------------------------+");
         System.out.println("|                                                                                |");
         

         System.out.println("                                # Tel  : "+number+"                                ");
         System.out.println("                                # Name : "+name+"                                  ");
         System.out.println("+-----------------------+-----------------+------------------+-------------------+");
         System.out.println("|                       |       Qty       |   Unit Price     |       Price       |");
         System.out.println("+-----------------------+-----------------+------------------+-------------------+");
         System.out.println("|     #Basmathi         |      "+bas+"         |        "+Basmathi+"     |     "+bas*Basmathi+"        |");
         System.out.println("|                       |                 |                  |                   |"); 
         System.out.println("|     #Dhal             |      "+dha+"          |        "+Dhal+"     |     "+dha*Dhal+"         |");
         System.out.println("|                       |                 |                  |                   |");
         System.out.println("|     #Sugar            |      "+sug+"          |        "+Sugar+"     |     "+sug*Sugar+"         |");
         System.out.println("|                       |                 |                  |                   |");
         System.out.println("|     #Highland         |      "+hig+"          |        "+Highland+"    |     "+hig*Highland+"        |");
         System.out.println("|                       |                 |                  |                   |");
         System.out.println("|     #Youghurt         |      "+yog+"          |        "+Yoghurt+"      |     "+yog*Yoghurt+"         |");
         System.out.println("|                       |                 |                  |                   |");
         System.out.println("|     #Flour            |      "+flo+"          |        "+Flour+"     |     "+flo*Flour+"         |");
         System.out.println("|                       |                 |                  |                   |");
         System.out.println("|     #Soap             |      "+soa+"          |        "+Soap+"     |     "+soa*Soap+"        |");
         System.out.println("|                       |                 |                  |                   |");
         System.out.println("+-----------------------+-----------------+------------------+-------------------+");
         double Total=bas*Basmathi +dha*Dhal+sug*Sugar +hig*Highland+yog*Yoghurt +flo*Flour+soa*Soap;
         System.out.println("|                                         | Total            |          "+Total+"   |");
         System.out.println("|                                         +------------------+-------------------+");
         double Discount=Total/10;
         System.out.println("|                                         | Discount(10%)    |          "+Discount+"    |");
         System.out.println("|                                         +------------------+-------------------+");
         double Price=Total-Discount; 
         System.out.println("|                                         | Price            |          "+Price+"   |");
         System.out.println("|-----------------------------------------+------------------+-------------------+");       
         System.out.println();
         double netamount=Price;
         System.out.println("Enter the cash Amount : ");
         int cash=input.nextInt();
         double change;
         change=cash-netamount;
         System.out.println("+-----------------------+--------------------+");
         System.out.println("|     NetAmount         |      "+netamount+"        |");
         System.out.println("+-----------------------+--------------------+");
         System.out.println("|     Cash              |      "+cash+"         |");
         System.out.println("+-----------------------+--------------------+");       
         System.out.println("|     Change            |      "+change+"        |");
         System.out.println("+-----------------------+--------------------+");
         System.out.println();
         System.out.println();
         System.out.println("+------------------+-------------+");
	     System.out.println("|      Value       |      No     |");      
         System.out.println("+------------------+-------------+");
         int x,y,z;
         y=0;
         z=0;
         x=(int)change/5000;
	 System.out.println("|   Rs.5000        |   "+x+"         |"); 
         change=change-5000*x;
         y=y+x;
	 System.out.println("|------------------|-------------|");
         x=(int)change/2000*x;
	 System.out.println("|   Rs.2000        |   "+x+"         |");
         change=change-2000*x;
         y=y+x;
	 System.out.println("|------------------|-------------|");
         x=(int)change/1000;
	 System.out.println("|   Rs.1000        |   "+x+"         |");
         change=change-1000*x;
         y=y+x;
	 System.out.println("|------------------|-------------|");
         x=(int)change/500;
	 System.out.println("|   Rs.500         |   "+x+"         |");
         change=change-500*x; 
         y=y+x;
	 System.out.println("|------------------|-------------|");
         x=(int)change/100;
	 System.out.println("|   Rs.100         |   "+x+"         |");
         change=change-100*x;
         y=y+x;
	 System.out.println("|------------------|-------------|");
         x=(int)change/50;
	 System.out.println("|   Rs.50          |   "+x+"         |");
         change=change-50*x;
         y=y+x;
	 System.out.println("|------------------|-------------|");
         x=(int)change/20;
	 System.out.println("|   Rs.20          |   "+x+"         |");
         change=change-20*x;
         y=y+x;
	 System.out.println("|------------------|-------------|");
         x=(int)change/10;
	 System.out.println("|   Rs.10          |   "+x+"         |");
         change=change-10*x;
         y=y+x;
	 System.out.println("|------------------|-------------|");
         x=(int)change/5;
	 System.out.println("|   Rs.5           |   "+x+"         |");
         change=change-5*x;
         y=y+x;
	 System.out.println("|------------------|-------------|");
         x=(int)change/2;
	 System.out.println("|   Rs.2           |   "+x+"         |");
         change=change-2*x;
         y=y+x;
	 System.out.println("|------------------|-------------|");
         x=(int)change/1;
     System.out.println("|   Rs.1           |   "+x+"         |"); 
         change=change-1*x;
         y=y+x; 
 	 System.out.println("+------------------+-------------+");
	 System.out.println("| No of Notes      |   "+y+"        |");
	 System.out.println("+------------------+-------------+");	
     System.out.println("| No of Coins      |   "+z+"         |");
	 System.out.println("+------------------+-------------+");
	 System.out.println();
	 System.out.println();
	 System.out.println("-------------------------------------------");
	 System.out.println("       THANK YOU FOR SHOPPING WITH US      "); 
	 System.out.println("-------------------------------------------");



   
      }
}
